publish:
  - app:
      name: 微信pi
      发布日期: 20180101
      版本: 1.0
  - app:
      name: 支付宝
      发布日期: 20190101
      版本: 1.0
  - app:
      name: 精品段子
      发布日期: 20200224
      版本: 1.0

develope:
  - app:

